name: Increment Deployment on EC2

on:
  push:
    branches: [ "main" ]

jobs:
  increment-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check out repository
        env: 
          PRIVATE_KEY: ${{ secrets.EC2_PEM }}
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USER_NAME: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << 'ENDSSH'
            cd /home/ec2-user/midterm-practice
            # Extract current DEPLOYMENT_COUNT from .env
            CURRENT_COUNT=$(grep '^DEPLOYMENT_COUNT=' .env | cut -d '=' -f2)
            # Increment and replace in .env
            NEW_COUNT=$((CURRENT_COUNT + 1))
            sed -i "s/^DEPLOYMENT_COUNT=.*/DEPLOYMENT_COUNT=${NEW_COUNT}/" .env
            echo "Updated DEPLOYMENT_COUNT to ${NEW_COUNT}"
            export $(cat .env | xargs) && \
            sed -i "s/const deploymentCount = \"[^\"]*\"/const deploymentCount = \"$DEPLOYMENT_COUNT\"/" index.html && \
            sed -i "s/const environment = \"[^\"]*\"/const environment = \"$ENVIRONMENT\"/" index.html && \
            sed -i "s/const location = \"\"/const location = \"$LOCATION\"/" index.html && \
            sudo systemctl restart nginx
          ENDSSH